"""create loan table

Revision ID: 85df233e8452
Revises: 05e2bda6c157
Create Date: 2026-10-08 16:13:43.331682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85df233e8452'
down_revision: Union[str, Sequence[str], None] = '05e2bda6c157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('emi', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('applied_on', sa.Date(), nullable=False),
    sa.CheckConstraint('amount >= 10000 AND amount <= 5000000', name='ck_loans_amount_range'),
    sa.CheckConstraint('interest_rate >= 0', name='ck_loans_interest_rate'),
    sa.CheckConstraint('tenure_months IN (12, 24, 36, 48, 60)', name='ck_loans_tenure'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    # ### end Alembic commands ###
